# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='mainCategory',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='bal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
